d = ["Kuerzel",
  "pat_id",
  "diagnosis1",
  "diagnosis2",
  "dob",
  "op_date_Surgery1",
  "op_date_Surgery2",
  "op_date_Surgery3",
  "op_code_Surgery1",
  "op_code_Surgery2",
  "op_code_Surgery3",
  "op_diagnosis_Surgery1",
  "op_diagnosis_Surgery2",
  "op_diagnosis_Surgery3",
  "pve_date",
  "pve",
  "study_id",
  "case_id",
  "age",
  "sex",
  "diagnosis_date",
  "primary_location",
  "T",
  "M",
  "N",
  "LK",
  "L",
  "V",
  "R",
  "G",
  "Pn",
  "RAS",
  "BRAF",
  "MSS",
  "crlm_met_syn",
  "crlm_procedure_planned",
  "crlm_procedure_realize",
  "clrm_bilobular",
  "multimodal",
  "two_staged",
  "date_fu",
  "status_fu",
  "recurrence_date",
  "recurrence_status",
  "recurrence_organ",
  "asa",
  "bmi",
  "alcohol",
  "smoking",
  "diabetes",
  "limax_initial",
  "limax_initial_date",
  "limax_second",
  "limax_second_date",
  
]

sql = "INSERT INTO mcrc_tabelle (%s) VALUES (%s)"# ON DUPLICATE KEY UPDATE"


sql_update = "UPDATE mcrc_tabelle SET SAPID  = %s, Geschlecht = %s, Geburtsdatum = %s, LastChanged = %s WHERE SAPID = %s"